# Generated by Django 3.1.2 on 2020-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='应聘者ID')),
                ('username', models.CharField(max_length=135, verbose_name='姓名')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='本科学校')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='专业')),
                ('degree', models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=135, verbose_name='学历')),
                ('test_score_of_general_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='综合能力测评成绩')),
                ('paper_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='笔试成绩')),
                ('first_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='初试分')),
                ('second_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='初试分')),
                ('hr_score', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR综合复试等级')),
            ],
            options={
                'verbose_name': '应聘者',
                'verbose_name_plural': '应聘者',
                'db_table': 'candidate',
            },
        ),
    ]
