# Generated by Django 3.1.2 on 2020-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='second_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='复试分'),
        ),
    ]
